// link:- https://youtu.be/Eivk4lyC00E?list=PLC3y8-rFHvwjPxNAKvZpdnsr41E0fCMMP

/*         MATH ALGORITHMS         */

// FIBONACCI SEQUENCE
// FACTORIAL OF A NUMBER
// PRIME NUMBER
// POWER OF TWO
// RECURSION
// FIBONACCI SEQUENCE WITH RECURSION
// FACTORIAL OF A NUMBER USING RECURSION
